const express = require('express');
const app = express();
const cors = require('cors');
const PORT = process.env.PORT || 3000;

app.use(cors());

const exercises = [
  {
    name: 'Pushup',
    image: 'https://www.fitnesseducation.edu.au/wp-content/uploads/2017/03/Pushups.jpg',
    video: 'https://youtu.be/IODxDxX7oi4?si=DCWtdyAcZ1tz5t_k',
    primaryMuscle: 'chest',
    secondaryMuscle: 'triceps',
    equipment: ['body'],
    _id: 1,
  },
  {
    name: 'Barbell Bench Press',
    image: 'https://cdn.muscleandstrength.com/sites/default/files/barbell-bench-press_0.jpg',
    video: 'https://youtu.be/wzq57DB5Ppg?si=Kvt-ghPjexq45Z0e',
    primaryMuscle: 'chest',
    secondaryMuscle: 'triceps',
    equipment: ['barbell', 'bench'],
    _id: 2,
  },
  {
    name: 'Dumbbell Incline Bench Press',
    image: 'https://hips.hearstapps.com/hmg-prod/images/dumbbell-press-1618499448.jpg',
    video: 'https://youtu.be/pA29ucBQxKU?si=k2gGweQsDZnfISaS',
    primaryMuscle: 'chest',
    secondaryMuscle: 'triceps',
    equipment: ['dumbbell', 'bench'],
    _id: 3,
  },
  {
    name: 'Barbell Bent-Over Row',
    image: 'https://hips.hearstapps.com/hmg-prod/images/bent-over-row-1579627763.jpg',
    video: 'https://youtu.be/pyBHPoC8Nzo?si=QavZXcX1bCzaZ9pX',
    primaryMuscle: 'back',
    secondaryMuscle: 'biceps',
    equipment: ['barbell'],
    _id: 4,
  },
  {
    name: 'Seated Cable Row',
    image: 'https://fitnessstars.weebly.com/uploads/5/8/8/7/58879495/1225337_orig.png',
    video: 'https://youtu.be/UCXxvVItLoM?si=KnmYrTUvcJZKq4zL',
    primaryMuscle: 'back',
    secondaryMuscle: 'biceps',
    equipment: ['cable'],
    _id: 5,
  },
  {
    name: 'Single Arm Dumbbell Row',
    image: 'https://boxlifemagazine.com/wp-content/uploads//2022/11/barbell-row-form-illus.webp',
    video: 'https://youtu.be/xl1YiqQY2vA?si=fdL4TrA9pBSnvIuU',
    primaryMuscle: 'back',
    secondaryMuscle: 'biceps',
    equipment: ['dumbbell', 'bench'],
    _id: 6,
  },
  {
    name: 'Barbell Overhead Press',
    image: '',
    video: '',
    primaryMuscle: 'shoulders',
    secondaryMuscle: 'triceps',
    equipment: ['barbell'],
    _id: 7,
  },
  {
    name: 'Seated Dumbbell Shoulder Press',
    image: '',
    video: '',
    primaryMuscle: 'shoulders',
    secondaryMuscle: 'triceps',
    equipment: ['dumbbell', 'bench'],
    _id: 8,
  },
  {
    name: 'Machine Shoulder Press',
    image: '',
    video: '',
    primaryMuscle: 'shoulders',
    secondaryMuscle: 'triceps',
    equipment: ['machine'],
    _id: 9,
  },
  {
    name: 'Pullup',
    image: '',
    video: '',
    primaryMuscle: 'back',
    secondaryMuscle: 'biceps',
    equipment: ['body'],
    _id: 10,
  },
  {
    name: 'Lat Pulldown',
    image: '',
    video: '',
    primaryMuscle: 'back',
    secondaryMuscle: 'biceps',
    equipment: ['machine'],
    _id: 11,
  },
  {
    name: 'Cable Straight Arm Pulldown',
    image: '',
    video: '',
    primaryMuscle: 'back',
    secondaryMuscle: 'serratus anterior',
    equipment: ['cable'],
    _id: 12,
  },
  {
    name: 'Barbell Back Squat',
    image: '',
    video: '',
    primaryMuscle: 'quads',
    secondaryMuscle: 'glutes',
    equipment: ['barbell'],
    _id: 13,
  },
  {
    name: 'Kettlebell Goblet Squat',
    image: '',
    video: '',
    primaryMuscle: 'quads',
    secondaryMuscle: 'glutes',
    equipment: ['kettlebell'],
    _id: 14,
  },
  {
    name: 'Air Squat',
    image: '',
    video: '',
    primaryMuscle: 'quads',
    secondaryMuscle: 'glutes',
    equipment: ['body'],
    _id: 15,
  },
  {
    name: 'Barbell Deadlift',
    image: '',
    video: '',
    primaryMuscle: 'hamstrings',
    secondaryMuscle: 'glutes',
    equipment: ['barbell'],
    _id: 16,
  },
  {
    name: 'Kettlebell Romanian Deadlift',
    image: '',
    video: '',
    primaryMuscle: 'hamstrings',
    secondaryMuscle: 'glutes',
    equipment: ['kettlebell'],
    _id: 17,
  },
  {
    name: 'Barbell Good Morning',
    image: '',
    video: '',
    primaryMuscle: 'hamstrings',
    secondaryMuscle: 'glutes',
    equipment: ['barbell'],
    _id: 18,
  },
  {
    name: 'Dumbbell Lunge',
    image: '',
    video: '',
    primaryMuscle: 'quads',
    secondaryMuscle: 'glutes',
    equipment: ['dumbbell'],
    _id: 19,
  },
  {
    name: 'Dumbbell Bulgarian Split Squat',
    image: '',
    video: '',
    primaryMuscle: 'quads',
    secondaryMuscle: 'glutes',
    equipment: ['dumbbell', 'bench'],
    _id: 20,
  },
  {
    name: 'Dumbbell Step Up',
    image: '',
    video: '',
    primaryMuscle: 'quads',
    secondaryMuscle: 'glutes',
    equipment: ['dumbbell', 'bench'],
    _id: 21,
  },
  {
    name: 'Plank',
    image: '',
    video: '',
    primaryMuscle: 'core',
    secondaryMuscle: '',
    equipment: ['body'],
    _id: 22,
  },
  {
    name: 'Crunch',
    image: '',
    video: '',
    primaryMuscle: 'core',
    secondaryMuscle: '',
    equipment: ['body'],
    _id: 23,
  },
  {
    name: 'Dead Bug',
    image: '',
    video: '',
    primaryMuscle: 'core',
    secondaryMuscle: '',
    equipment: ['body'],
    _id: 24,
  },
  {
    name: 'Dumbbell Bicep Curl',
    image: '',
    video: '',
    primaryMuscle: 'biceps',
    secondaryMuscle: '',
    equipment: ['dumbbell'],
    _id: 25,
  },
  {
    name: 'Cable Tricep Pushdown',
    image: '',
    video: '',
    primaryMuscle: 'triceps',
    secondaryMuscle: '',
    equipment: ['cable'],
    _id: 26,
  },
  {
    name: 'Dumbbell Lateral Raise',
    image: '',
    video: '',
    primaryMuscle: 'shoulders',
    secondaryMuscle: '',
    equipment: ['dumbbell'],
    _id: 27,
  },
  {
    name: 'Dumbbell Front Raise',
    image: '',
    video: '',
    primaryMuscle: 'shoulders',
    secondaryMuscle: '',
    equipment: ['dumbbell'],
    _id: 28,
  },
  {
    name: 'Dumbbell Rear Delt Fly',
    image: '',
    video: '',
    primaryMuscle: 'shoulders',
    secondaryMuscle: '',
    equipment: ['dumbbell'],
    _id: 29,
  },
  {
    name: 'Dumbbell Hammer Curl',
    image: '',
    video: '',
    primaryMuscle: 'biceps',
    secondaryMuscle: '',
    equipment: ['dumbbell'],
    _id: 30,
  },
  {
    name: 'Dumbbell Skull Crusher',
    image: '',
    video: '',
    primaryMuscle: 'triceps',
    secondaryMuscle: '',
    equipment: ['dumbbell'],
    _id: 31,
  },
  {
    name: 'Dumbbell Shoulder Shrug',
    image: '',
    video: '',
    primaryMuscle: 'traps',
    secondaryMuscle: '',
    equipment: ['dumbbell'],
    _id: 32,
  },
  {
    name: 'Dumbbell Upright Row',
    image: '',
    video: '',
    primaryMuscle: 'traps',
    secondaryMuscle: '',
    equipment: ['dumbbell'],
    _id: 33,
  },
  {
    name: 'Dumbbell Bent Over Reverse Fly',
    image: '',
    video: '',
    primaryMuscle: 'back',
    secondaryMuscle: '',
    equipment: ['dumbbell'],
    _id: 34,
  },
  {
    name: 'Dumbbell Lying Tricep Extension',
    image: '',
    video: '',
    primaryMuscle: 'triceps',
    secondaryMuscle: '',
    equipment: ['dumbbell'],
    _id: 35,
  },
];

app.get('/', (req, res) => {
  res.sendFile(__dirname + '/index.html');
});

app.get('/api/exercises', (req, res) => {
  res.json(exercises);
});

app.get('/api/exercises/:id', (req, res) => {
  const exercise = exercises.find((exercise) => exercise._id === req.params.id);
  res.json(exercise);
});

app.listen(PORT, () => {
  console.log(`Server listening on port ${PORT}`);
});
